apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: tech-challenge
data:
  PORT: "8000"
  LOG_LEVEL: "info"
  AWS_REGION: "us-east-1"
  AWS_DYNAMODB_TABLE: "analytics"
  AWS_SQS_URL: "http://localstack:4566/000000000000/queue"
