apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: techchallenge
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9hdXRoOmF1dGhAYXV0aGRiOjU0MzIvYXV0aGRi
  MASTER_KEY: YWRtaW4tc2VjcmV0by0xMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: flag-secrets
  namespace: techchallenge
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9mbGFnOmZsYWdAZmxhZ2RiOjU0MzIvZmxhZ2Ri
---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-secrets
  namespace: techchallenge
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly90YXJnZXQ6dGFyZ2V0QHRhcmdldGRiOjU0MzIvdGFyZ2V0ZGI=
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secrets
  namespace: techchallenge
type: Opaque
data:
  REDIS_URL: cmVkaXM6Ly9yZWRpczo2Mzc5
  AWS_SQS_URL: aHR0cDovL2xvY2Fsc3RhY2s6NDU2Ni8wMDAwMDAwMDAwMDAvcXVldWU=
  AWS_ACCESS_KEY_ID: dGVzdA==
  AWS_SECRET_ACCESS_KEY: dGVzdA==
  SERVICE_API_KEY: dG1fa2V5XzliYWJkYTQ2NGI1Y2M5Y2U4M2MzNjhjMzBhNGUwNDhlYWZjMGMxMGUxOWYyY2QyNDBmNjZlM2I4NTE3NmExNjQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
  namespace: techchallenge
type: Opaque
data:
  AWS_SQS_URL: aHR0cDovL2xvY2Fsc3RhY2s6NDU2Ni8wMDAwMDAwMDAwMDAvcXVldWU=
  AWS_ACCESS_KEY_ID: dGVzdA==
  AWS_SECRET_ACCESS_KEY: dGVzdA==
  AWS_DYNAMODB_TABLE: YW5hbHl0aWNz
