apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: analytics-hpa
  namespace: NAMESPACE_AJUSTAR   # <-- Ajustar para o namespace real (ex.: togglemaster)
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics-deployment    # <-- Ajustar se o nome do Deployment for diferente
  minReplicas: 1                  # No AWS Academy não dá para escalar para 0
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60  # alvo de utilização média de CPU (%)
  # Comportamento opcional (deixa o scale down mais estável)
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
