apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-service-config
  namespace: tech-challenge
data:
  PORT: "8000"
  LOG_LEVEL: "info"
  AUTH_SERVICE_URL: "http://auth-service.tech-challenge.svc.cluster.local:8000"
