apiVersion: v1
kind: Service
metadata:
  name: targeting-service
  namespace: tech-challenge
  labels:
    app: targeting-service
spec:
  type: ClusterIP
  selector:
    app: targeting-service
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  sessionAffinity: None
