apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-sa
  namespace: <NAMESPACE>
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<ROLE_NAME_IRSA>  # Ajuste para o ARN da Role criada/gerenciada pelo eksctl
